services:
  eshopdb:
    image: postgres

  distributedcache:
    image: redis

  seq:
    image: datalust/seq

  messagebus:
    image: rabbitmq:management
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    

volumes:
  postgres_eshopdb: